P:
  START:
    - "8:40"
    - "10:10"
    - "12:15"
    - "13:45"
    - "15:15"
    - "16:45"
  END:
    - "9:55"
    - "11:25"
    - "13:30"
    - "15:00"
    - "16:30"
    - "18:00"
TERM:
  # 学年暦 ref
  # http://www.tsukuba.ac.jp/campuslife/calendar/
  BEGIN:
    春:
      A: 2016/04/13
      B: 2016/05/18
      C: 2016/07/05
    夏: 2016/08/11
    秋:
      A: 2016/10/03
      B: 2016/11/07
      C: 2017/01/10
  # 13:00 となっているのは、GMTで指定するため (JSTなら、22:00)
  END:
    春:
      A: 2016/05/17 13:00
      B: 2016/07/04 13:00
      C: 2016/08/10 13:00
    夏: 2016/09/30 13:00
    秋:
      A: 2016/11/08 13:00
      B: 2017/01/09 13:00
      C: 2017/02/16 13:00
database:
  filename: "kamoku.db"
  table_name: "kamoku"
  column_names:
    - "code"
    - "name"
    - "method"
    - "unit"
    - "grade"
    - "term"
    - "period"
    - "location"
    - "teacher"
    - "abstruct"
    - "note"
    - "research_students"
    - "reason"
    - "english_name"
    - "time"
